repos:
-   repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3.12
      stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
